variables:
  GIT_STRATEGY: none
  PACKAGE_NAME:         moodle-rwth-cardbox
  PACKAGE_CAPABILITIES: moodle-rwth-rwth_cardbox
  PACKAGE_SUMMARY:      RWTH plugin for learning with flashcards.
  PACKAGE_DESCRIPTION:  Package to install the Moodle Plugin cardbox.

stages:
  - version-php
  - spec
  - archive
  - build
  - deploy
  - update
  - dbupgrade

parse-version-php:
  stage: version-php
  variables:
    GIT_STRATEGY: clone
  script:
    - PLUGIN_COMPONENT=$(grep -Po "^\s*\\\$plugin->component\s*=\s*['\"]\K[a-z_]+" version.php)
    - echo "PLUGIN_COMPONENT=$PLUGIN_COMPONENT" > plugin.env
    - echo "PLUGIN_TYPE=$(echo $PLUGIN_COMPONENT | grep -Po "^[a-z]+")" >> plugin.env
    - echo "PLUGIN_NAME=$(echo $PLUGIN_COMPONENT | grep -Po "^[a-z]+_\K[a-z0-9_]+")" >> plugin.env
    - echo "PLUGIN_VERSION=$(grep -Po "^\s*\\\$plugin->version\s*=\s*\K[0-9]{10}" version.php)" >> plugin.env
    - echo "PLUGIN_RELEASE=$(grep -Po "^\s*\\\$plugin->release\s*=\s*['\"].*\K[0-9]+\.[0-9]+(\.[0-9]+)" version.php)" >> plugin.env
    - echo "PLUGIN_REQUIRES=$(grep -Po "^\s*\\\$plugin->requires\s*=\s*\K[0-9]{10}" version.php)" >> plugin.env
  only:
    - testing
    - integration
    - production
  tags:
    - git
  artifacts:
    reports:
      dotenv: plugin.env
    expire_in: 1 week

plugin-types:
  stage: version-php
  script:
    # script copied from https://docs.moodle.org/dev/Plugin_types
    - script=$(mktemp plugintypes.XXXXXXXXXX)
    - |
      cat > $script <<EOF
      <?php
      define('CLI_SCRIPT', true);
      require('/var/www/html/moodle/config.php');

      \$pluginman = core_plugin_manager::instance();

      foreach (\$pluginman->get_plugin_types() as \$type => \$dir) {
          \$dir = substr(\$dir, strlen(\$CFG->dirroot) + 1);
          echo "\$type \$dir\n";
      }
      EOF
    - php $script > plugintypes.txt
    - rm $script
  only:
    - testing
    - integration
    - production
  tags:
    - moodle-web-t01
  artifacts:
    paths:
      - plugintypes.txt
    expire_in: 1 week

plugin-path:
  stage: version-php
  needs:
    - parse-version-php
    - plugin-types
  script:
    - PLUGIN_TYPE_PATH=$(grep "^${PLUGIN_TYPE} " plugintypes.txt | cut -d " " -f 2)
    - echo "PLUGIN_TYPE_PATH=${PLUGIN_TYPE_PATH}" > pluginpath.env
    - PLUGIN_PATH=${PLUGIN_TYPE_PATH}/${PLUGIN_NAME}
    - echo "PLUGIN_PATH=${PLUGIN_PATH}" >> pluginpath.env
  only:
    - testing
    - integration
    - production
  tags:
    - git
  artifacts:
    reports:
      dotenv: pluginpath.env
    expire_in: 1 week

package-version:
  stage: spec
  needs:
    - parse-version-php
  script:
    - PACKAGE_VERSION=${PLUGIN_RELEASE}
    - echo "PACKAGE_VERSION=$PACKAGE_VERSION" > packageversion.env
    - PACKAGE_RELEASE=${PLUGIN_VERSION}
    # check repository for existing packages with same version and release
    # "set +e" disables exit on non-zero exit status (grep exits with 1 if nothing found)
    - set +e
    - packages=($(wget -O- http://moodle-rpms.itc.rwth-aachen.de/moodle-$CI_COMMIT_BRANCH/ | grep -Po ">\K${PACKAGE_NAME}-${PACKAGE_VERSION}-${PACKAGE_RELEASE}[^<]*"))
    - set -e
    - maxsubrelease=0
    - |
      for package in "${packages[@]}"
      do
        set +e
        subrelease=$(echo $package | grep -Po "${PACKAGE_RELEASE}\.\K[0-9]+")
        set -e
        if [ -z $subrelease ]
        then
          subrelease=0
        fi
        if [ $subrelease -gt $maxsubrelease ]
        then
          maxsubrelease=$subrelease
        fi
      done
    # append subrelease number to release if necessary
    - |
      if [ ${#packages[@]} -gt 0 ]
      then
        PACKAGE_RELEASE=${PACKAGE_RELEASE}.$( expr $maxsubrelease + 1)
      fi
    - echo "PACKAGE_RELEASE=$PACKAGE_RELEASE" >> packageversion.env
  only:
    - testing
    - integration
    - production
  tags:
    - git
  artifacts:
    reports:
      dotenv: packageversion.env
    expire_in: 1 week

required-moodle-version:
  stage: spec
  needs:
    - parse-version-php
  script:
    - wget -O artifacts.zip "${CI_API_V4_URL}/projects/moodle_l2p%2Fmoodle-releases/jobs/artifacts/main/download?job=update-releases&job_token=$CI_JOB_TOKEN"
    - unzip artifacts.zip
    - script=$(mktemp packagerequiresmoodle.XXXXXXXXXX)
    - |
      cat > $script <<EOF
      import json

      with open('releases.json') as f:
        data = json.load(f)
        print(data['${PLUGIN_REQUIRES}'])
      EOF
    - PACKAGE_REQUIRES_MOODLE=$(python3 $script)
    - echo "PACKAGE_REQUIRES_MOODLE=$PACKAGE_REQUIRES_MOODLE" > packagerequiresmoodle.env
    - rm $script
  only:
    - testing
    - integration
    - production
  tags:
    - git
  artifacts:
    reports:
      dotenv: packagerequiresmoodle.env
    expire_in: 1 week

generate-spec:
  stage: spec
  needs:
    - parse-version-php
    - plugin-path
    - package-version
    - required-moodle-version
  script:
    - |
      cat > ${CI_PROJECT_DIR}/${PACKAGE_NAME}.spec <<EOF
      Name:        ${PACKAGE_NAME}
      Version:     ${PACKAGE_VERSION}
      Release:     ${PACKAGE_RELEASE}
      Summary:     ${PACKAGE_SUMMARY}
      
      License:     GPL
      URL:         ${CI_PROJECT_URL}
      Source0:     ${PLUGIN_NAME}.tar.gz
      AutoReqProv: No
      Requires:    moodle-rwth >= ${PACKAGE_REQUIRES_MOODLE}
      Provides:    ${PACKAGE_CAPABILITIES}
      
      
      %description
      ${PACKAGE_DESCRIPTION}
      
      %prep
      %setup -q -n ${PLUGIN_NAME}
      
      
      %install
      mkdir -p \$RPM_BUILD_ROOT
      install -d %{_builddir} \$RPM_BUILD_ROOT/var/www/html/moodle/${PLUGIN_TYPE_PATH}/
      cp -r %{_builddir}/${PLUGIN_NAME} \$RPM_BUILD_ROOT/var/www/html/moodle/${PLUGIN_TYPE_PATH}
      
      %post
      chown -R apache: /var/www/html/moodle/${PLUGIN_PATH}
      chmod a-w -R /var/www/html/moodle
      
      %files
      /var/www/html/moodle/${PLUGIN_PATH}
      EOF
  only:
    - testing
    - integration
    - production
  tags:
    - git
  artifacts:
    paths:
      - $PACKAGE_NAME.spec
    expire_in: 1 week

archive:
  stage: archive
  needs:
    - parse-version-php
  variables:
    GIT_STRATEGY: clone
  script:
    - git archive --format=tar.gz --prefix=${PLUGIN_NAME}/ HEAD > ${PLUGIN_NAME}.tar.gz
  only:
    - testing
    - integration
    - production
  tags:
    - git
  artifacts:
    paths:
      - "*.tar.gz"
    expire_in: 1 week

build:
  stage: build
  needs:
    - generate-spec
    - archive
  script:
    - mkdir SOURCES SPECS
    - mv cardbox.tar.gz SOURCES
    - mv $PACKAGE_NAME.spec SPECS
    - rpmbuild -ba --define "_topdir `pwd`" SPECS/$PACKAGE_NAME.spec
  only:
    - testing
    - integration
    - production
  tags:
    - git
  dependencies:
    - archive
    - generate-spec
  artifacts:
      paths:
        - RPMS/x86_64/*.rpm
      expire_in: 1 week

deploy:
  stage: deploy
  needs:
    - build
  dependencies:
    - build
  script:
    - cp RPMS/x86_64/*.rpm /data/repos/moodle-$CI_COMMIT_BRANCH
    - createrepo /data/repos/moodle-$CI_COMMIT_BRANCH
  only:
    - testing
    - integration
    - production
  tags:
    - git

update-t01:
  stage: update
  needs:
    - deploy
  script:
    - sudo yum clean all
    - sudo yum update $PACKAGE_NAME --disableexclude=all -y
  only:
    - testing
  tags:
    - moodle-web-t01

update-t02:
  stage: update
  needs:
    - deploy
  script:
    - sudo yum clean all
    - sudo yum update $PACKAGE_NAME --disableexclude=all -y
  only:
    - testing
  tags:
    - moodle-web-t02

dbupgrade_testing:
  stage: dbupgrade
  needs:
    - update-t01
  script:
    - sudo -u apache php /var/www/html/moodle/admin/cli/upgrade.php --non-interactive
  only:
    - testing
  tags:
    - moodle-web-t01
