variables:
  GIT_STRATEGY: clone
stages:
  - prebuild
  - build
  - deploy
  - update
  - dbupgrade

archive:
    stage: prebuild
    script:
      - git archive --format=tar.gz --prefix=cardbox/ HEAD > $CI_PROJECT_DIR/cardbox.tar.gz
    only:
      - testing
      - integration
      - production
    tags:
      - git
    artifacts:
      paths:
        - cardbox.tar.gz
      expire_in: 1 week

generate-spec:
    stage: prebuild
    script:
      # read version.php
      - version=$(grep -Po "^\s*\\\$plugin->release\s*=\s*['\"].*\K[0-9]+\.[0-9]+(\.[0-9]+)" version.php)
      - release=$(grep -Po "^\s*\\\$plugin->version\s*=\s*\K[0-9]{10}" version.php)
      # check repository for existing packages with same version and release
      # "set +e" disables exit on non-zero exit status (grep exits with 1 if nothing found)
      - set +e
      - packages=($(curl http://moodle-rpms.itc.rwth-aachen.de/moodle-$CI_COMMIT_BRANCH/ | grep -Po ">\Kmoodle-rwth-cardbox-$version-$release[^<]*"))
      - set -e
      - maxsubrelease=0
      - |
        for package in "${packages[@]}"
        do
          set +e
          subrelease=$(echo $package | grep -Po "$release\.\K[0-9]+")
          set -e
          if [ -z $subrelease ]
          then
            subrelease=0
          fi
          if [ $subrelease -gt $maxsubrelease ]
          then
            maxsubrelease=$subrelease
          fi
        done
      # append subrelease number to release if necessary
      - |
        if [ ${#packages[@]} -gt 0 ]
        then
          release=$release.$( expr $maxsubrelease + 1)
        fi
      # generate spec file
      - |
        cat > $CI_PROJECT_DIR/moodle-rwth-cardbox.spec <<EOF
        Name:       moodle-rwth-cardbox
        Version:    $version
        Release:    $release
        Summary:    RWTH plugin for learning with flashcards.
        
        License:    GPL
        URL:        https://git.rwth-aachen.de/moodle_l2p/cardbox
        Source0:    cardbox.tar.gz
        AutoReqProv:     No
        Requires:    moodle-rwth >= 3.5
        Provides:    moodle-rwth-rwth_cardbox
        
        
        %description
        Package to install the Moodle Plugin cardbox.
        
        %prep
        %setup -q -n cardbox
        
        
        %install
        mkdir -p \$RPM_BUILD_ROOT
        install -d %{_builddir} \$RPM_BUILD_ROOT/var/www/html/moodle/mod/
        cp -r %{_builddir}/cardbox \$RPM_BUILD_ROOT/var/www/html/moodle/mod
        
        %post
        cd /var/www/html/moodle/mod
        chown -R apache: cardbox
        chmod a-w -R /var/www/html/moodle
        
        %files
        /var/www/html/moodle/mod/cardbox
        EOF
    only:
      - testing
      - integration
      - production
    tags:
      - git
    artifacts:
      paths:
        - moodle-rwth-cardbox.spec
      expire_in: 1 week

build:
    stage: build
    script:
      - mkdir SOURCES SPECS
      - mv cardbox.tar.gz SOURCES
      - mv moodle-rwth-cardbox.spec SPECS
      - rpmbuild -ba --define "_topdir `pwd`" SPECS/moodle-rwth-cardbox.spec
    only:
      - testing
      - integration
      - production
    tags:
      - git
    dependencies:
      - archive
      - generate-spec
    artifacts:
       paths:
          - RPMS/x86_64/*.rpm
       expire_in: 1 week

deploy:
    stage: deploy
    dependencies:
      - build
    script:
      - cp RPMS/x86_64/*.rpm /data/repos/moodle-$CI_COMMIT_BRANCH
      - createrepo /data/repos/moodle-$CI_COMMIT_BRANCH
    only:
      - testing
      - integration
      - production
    tags:
      - git

update-t01:
    stage: update
    dependencies:
      - deploy
    script:
      - sudo yum clean all
      - sudo yum update moodle-rwth-cardbox --disableexclude=all -y
    only:
      - testing
    tags:
      - moodle-web-t01

update-t02:
    stage: update
    dependencies:
      - deploy
    script:
      - sudo yum clean all
      - sudo yum update moodle-rwth-cardbox --disableexclude=all -y
    only:
      - testing
    tags:
      - moodle-web-t02

dbupgrade_testing:
    stage: dbupgrade
    dependencies:
      - update-t01
    script:
      - sudo -u apache php /var/www/html/moodle/admin/cli/upgrade.php --non-interactive
    only:
      - testing
    tags:
      - moodle-web-t01
